### PR TITLE
Added Send Password Setup Email Feature

### PR DESCRIPTION
**Pull request by NightFall28**
The workflow is able to send the user an email to set up a password (overwriting the default password)

### CODE REVIEW

**Comment by NightFall28** [comment]
Temporary using Firebase's send password function, need update in future.

**Comment by MarkusCDev** [comment]
Quality of Life, css changes, and workflow addition merge

**Review by MarkusCDev — COMMENTED** [review]
quality of life changes, css, and workflow addition

**Review by seaniori21 — APPROVED** [review]
Looks good to me

**Pull request merged**
